- name: deploy to root
  become: true
  become_user: "{{jetty_user}}"
  copy:
    remote_src: true
    src: "{{ download_dir }}/openig-war-4.0.0.war"
    dest: "{{jetty_home}}/webapps/root.war"
  register: openig_war

- name: restart jetty
  become: true
  service:
    name: jetty
    enabled: yes
    state: restarted
  when: openig_war.changed
