---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  playbook: playbook.yml

platforms:
#  - name: ubuntu-14.04
  - name: centos-6.7

suites:
  - name: RP
    provisioner:
      hosts: RP
