---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  playbook: playbook.yml

platforms:
#  - name: ubuntu-14.04
  - name: centos-6.7
    driver:
      box: bento/centos-6.7

suites:
  - name: RP
    driver:
      name: vagrant
      synced_folders:
        - ["modules", "/tmp/modules"]
      network:
        - ["private_network", { ip: "192.168.33.10" }]
    provisioner:
      hosts: RP
