- name: create jetty group
  group:
    name: jetty

- name: create jetty user
  user:
    name: jetty
    group: jetty
    append: yes

- name: download jetty
  get_url:
    url: "{{ jetty_dounload_url }}"
    dest: "/tmp/{{ jetty_archive }}"
    validate_certs: no
#    sha256sum: "{{ jetty_sha256 }}" チェックサムが無かった。怖い。

- name: should exist base dir
  file:
    dest: "{{ base_dir }}"
    state: directory
    recurse: true
    mode: 0755

- name: extract jetty
  become: true
  environment:
    LANG: C
    LC_ALL: C
    LC_MESSAGES: C
  unarchive:
    copy: no
    src: "/tmp/{{ jetty_archive }}"
    dest: "{{ base_dir }}"
    creates: "{{ jetty_dir }}"

- name: create symlink
  file:
    src: "{{ jetty_dir }}"
    dest: "{{ jetty_home }}"
    state: link

- name: add jetty to init.d
  file:
    src: "{{ jetty_home }}/bin/jetty.sh"
    dest: "/etc/init.d/jetty"
    state: link

- name: create jetty config
  blockinfile:
    create: yes
    dest: /etc/default/jetty
    mode: 0644
    block: |
      JETTY_HOME={{ jetty_home }}
      JAVA={{ JAVA_HOME }}/bin/java

- name: jetty service
  service:
    name: jetty
    enabled: yes
    state: restarted
