- name: create jetty group
  become: true
  group:
    name: jetty

- name: create jetty user
  become: true
  user:
    name: "{{ jetty_user }}"
    group: "{{ jetty_group }}"
    append: yes

- name: download jetty
  get_url:
    url: "{{ jetty_dounload_url }}"
    dest: "{{ download_dir }}/{{ jetty_archive }}"
    validate_certs: no
#    sha256sum: "{{ jetty_sha256 }}" チェックサムが無かった。怖い。

- name: extract jetty
  become: true
  environment:
    LANG: C
    LC_ALL: C
    LC_MESSAGES: C
  unarchive:
    copy: no
    src: "{{ download_dir }}/{{ jetty_archive }}"
    dest: "{{ base_dir }}"
    creates: "{{ jetty_dir }}"
    owner: "{{ jetty_user }}"
    group: "{{ jetty_group }}"

- name: create symlink
  become: true
  file:
    src: "{{ jetty_dir }}"
    dest: "{{ jetty_home }}"
    state: link

- name: add jetty to init.d
  become: true
  file:
    src: "{{ jetty_home }}/bin/jetty.sh"
    dest: "/etc/init.d/jetty"
    state: link
  register: jetty_init_d

- name: create jetty config
  become: true
  blockinfile:
    create: yes
    dest: /etc/default/jetty
    mode: 0644
    block: |
      JETTY_HOME={{ jetty_home }}
      JETTY_USER={{ jetty_user }}
      JETTY_HOST=0.0.0.0
      JAVA={{ JAVA_HOME }}/bin/java
  register: jetty_config

- name: jetty service
  become: true
  service:
    name: jetty
    enabled: yes
    state: restarted
  when: jetty_init_d.changed or jetty_config.changed

- name: jetty service started
  become: true
  service:
    name: jetty
    enabled: yes
    state: started
  when: not (jetty_init_d.changed or jetty_config.changed)
