- name: download java
  get_url:
    url: "{{ java_dounload_url }}"
    dest: "{{ download_dir }}/{{ java_archive }}"
    validate_certs: no
    headers: "Cookie: ' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'"
    sha256sum: "{{ java_sha256 }}"

- name: extract java
  become: true
  environment:
    LANG: C
    LC_ALL: C
    LC_MESSAGES: C
  unarchive:
    copy: no
    src: "{{ download_dir }}/{{ java_archive }}"
    dest: "{{ base_dir }}"
    creates: "{{ jdk_dir }}"

- name: create symlink
  become: true
  file:
    src: "{{ jdk_dir }}"
    dest: "{{ JAVA_HOME }}"
    state: link

- name: add to path
  become: true
  blockinfile:
    create: yes
    dest: /etc/profile.d/java.sh
    mode: 0644
    block: |
      export JAVA_HOME={{ JAVA_HOME }}
      export PATH=$PATH:$JAVA_HOME/bin
